---
title: "NCCEH Data Tools"
author: "Latest version of this document: [Link](https://raw.githack.com/timbender-ncceh/ncceh_data_tools/main/README_NCCEH_data_tools.html?token=GHSAT0AAAAAABUWU2BLTOHA3RJN3WDERZIAYUHU2JA)"
date: "Last Updated: `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*The purpose of these tools are to provide simple, fast, and no-cost ways to complete tasks such as batch geocoding addresses that can be time-consuming, difficult, and even costly. They have been created by NCCEH Staff in the free, widely-used, and open-source 'R' software environment for statistial computing. Directions on installing and using the tools are provided below*

# Batch Geocoder
Provides a simple, fast, no-cost, batch geocoder of mailing addresses using the US Census Bureau's geocoding API. 

#### **Downloads:**
* Install 'R' on your PC/Mac/Linux (free download here <https://cran.r-project.org/>)
* Download geocoder tool to your computer (right-click [link](https://raw.githubusercontent.com/timbender-ncceh/ncceh_data_tools/main/batch_geocode.R?token=GHSAT0AAAAAABUWU2BKN2YWPHPFPPZWNA4GYUHTV5A), save-as "batch_geocode.R")
* Download example template .xlsx file to the same directory (right-click [link](https://github.com/timbender-ncceh/ncceh_data_tools/raw/main/batch_addresses_in.xlsx), save-as "batch_addresses_in.xlsx")

#### **Data Preparation**
* Input addresses must be in MS Excel file named "batch_addresses_in.xlsx" or tool won't work properly. 
* 

#### **Run Tool**
* Run 'batch_geocode.R' tool (directions here: <https://foo.com>)
* Review output CSV file results. 


## Github Source
* <https://github.com/timbender-ncceh/ncceh_data_tools>
